import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { VercelToolbar } from "@vercel/toolbar/next";
import { existsSync } from "fs";
import { join } from "path";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Check if project is linked to Vercel by checking for .vercel directory
  const isVercelLinked = existsSync(join(process.cwd(), ".vercel", "project.json"));
  const shouldInjectToolbar = process.env.NODE_ENV === "development" && isVercelLinked;
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {shouldInjectToolbar && <VercelToolbar />}
      </body>
    </html>
  );
}
